### ISSUE TITLE
Provide a way to replicate tet suite resources storage setup.

### ISSUE THREAD

**Issue by trollet91** [gem5/gem5#505]
Enchencement feature:

In our lab, we don't have access to external network everywhere.
Before gem5 v23, we used to duplicate the resources into an internal database.
This way we could run the test suite without accessing outside network. 

Since v23, the resource setup became much much more complex and I didn't find a way to replicate this setup internaly.

Providing an automated way to replicate the resource storage would allow:
- Using gem5 test suite in environment with no external network with miniml effort.
- Orgs can use their own servers to store the resources. Reduce the demand on UCDavis servers.

**Comment by powerjg** [comment]
cc: @Harshil2107

**Comment by Harshil2107** [comment]
I will work on an util that could copy the database and the downloaded resources to a local directory. I think it is possible but I need to test it to be sure.

**Comment by Harshil2107** [comment]
Do you require all resources in the database to be accessed without external connection or only the ones that are used in the tests?

I just want to confirm the use cases.

**Comment by trollet91** [comment]
The best flow would be for me:
1- Extract all the resources from the current database server.
2- User manualy moves all the resources from public network to internal network.
3- Re-create the current data base in a server located in the internal network. I don't know how easy it is to automate from a script.
3- Change gem5_default_config.py to point to the new database
![Screenshot 2023-10-26 at 09-41-50 gem5_gem5 The official repository for the gem5 computer-system architecture simulator](https://github.com/gem5/gem5/assets/33010274/f0d06da0-cfb5-4f82-a2e2-715815160e15)

**Comment by Harshil2107** [comment]
I created a PR with the script that would create an offline copy of the database. Tell me if I missed anything.

**Comment by trollet91** [comment]
Thanks @Harshil2107 , this seems to cover the point 1. I will test it tomorrow.
For the point 3, do you think it's also possible to script it?

**Comment by Harshil2107** [comment]
I think just moving the output to the internal server and changing the path in the `url` field should work.

This the the high level description of the script
- Get the resource JSON objects and make a `resources.json`
- Download the resources which have a `url` field.
- As gem5 works with local resources, the only requernment is that the `url` should start with `file://` followed by the absolute path of the resource. The script then modifies the `url` field of the resources in `resources.json` to these `file://absolute-path` so that they refer to the local downloads and not the cloud bucket.

All you would have to do is to update the config to use the JSON file. The config structure for using a JSON file in config is:
```
{
  "url" : JSON file path,
  "isMongo": False,
  }
  ```
  There are multiple ways to do it:
  - Set the GEM5_CONFIG env variable to point to a new config file. This will override the default config.
  
- Have a file named `gem5-config.json` in the current working directory. This will also override the default config.

- Use the GEM5_RESOURCE_JSON env variable to override the default config to use a JSON file or use the GEM5_RESOURCE_JSON_APPEND env variable to add a JSON file to the current config.

**Comment by Harshil2107** [comment]
I am closing this issue as the PR related to this issue is merged.

**Comment by kaddkaka** [comment]
Hi, I'm new to gem5. I would also like to run it in offline mode. Where do I start?
