### ISSUE TITLE
Pottential Bug in low_power_sweep.py

### ISSUE THREAD

**Issue by Nitesh8998** [gem5/gem5#590]
The tests related to low_power fails due to NameError in the file low_power_sweep.py

Version : gem5 version 23.0.1.0

No modifications made, running stable version

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

1. Compile gem5 with command  ``` scons  build/ALL/gem5.opt -j64 ```
2. Execute the simulation with

```
 /home/simulators/gem5-latest/build/ALL/gem5.opt /home/simulators/gem5-latest/configs/dram/low_power_sweep.py -p open_adaptive -r 2
```

**Terminal Output**

```shell
gem5 Simulator System.  https://www.gem5.org
gem5 is copyrighted software; use the --copyright option for details.

gem5 version 23.0.1.0
gem5 compiled Nov 22 2023 14:34:52
gem5 started Nov 22 2023 16:25:22
gem5 executing on arcortx3080.pc.ac.upc.edu, pid 1340484
command line: /home/simulators/gem5-latest/build/ALL/gem5.opt /home/nitesh/simulators/gem5-latest/configs/dram/low_power_sweep.py -p open_adaptive -r 2

NameError: name 'TrafficGen' is not defined

At:
  /home/simulators/gem5-latest/configs/dram/low_power_sweep.py(270): <module>
  src/python/m5/main.py(630): main

```

**Host Operating System**
Ubuntu 23.10

**Host ISA**
X86

**Compiler used**
gcc 10.5.0

**Comment by Harshil2107** [comment]
Hi @Nitesh8998,
The bug is probably due to the missing dependency of protobuf. gem5 doesnt not build the traffic generator is protobuf is not installed (see line https://github.com/gem5/gem5/blob/b99af93183b2f77781b6f4759bc06f717d3bb9bc/src/cpu/testers/traffic_gen/SConscript#L66).

The script should work if you install the dependency with the command
```
sudo apt install libprotobuf-dev protobuf-compiler libgoogle-perftools-dev
```
For more details take a look at building gem5 documentation https://www.gem5.org/documentation/learning_gem5/part1/building/.
