### ISSUE TITLE
Ruby recycle and stall_and_wait message delivery errors 

### ISSUE THREAD

**Issue by JenniferBrana** [gem5/gem5#799]
**Describe the bug**

I am implementing cache coherence protocols using Ruby and have encountered issues with both the "recycle" and "stall_and_wait" functions that cause deadly protocol errors. I have attempted to use both recycle and stall_and_wait to deal with messages that cannot be currently processed by the coherence protocol (referred to as "deferred messages" below). I describe the individual issues below: 

recycle: recycle moves the deferred request from the head of the queue to the tail to allow other messages to be processed immediately. I have encountered a case where this reordered deferred messages on the same message channel (for example, when there were two messages on the same network). When the receiving cache can later observe the deferred messages, the messages are observed out of order, causing the coherence protocol to believe the later message was sent before the earlier message. This causes a protocol deadlock in Ruby. 

stall_and_wait: stall_and_wait moves the deferred request into a separate structure tagged by an address. I have found that if there coherence protocol attempts to defer multiple messages using stall_and_wait, the earlier message which was deferred is overwritten by later calls to stall_and_wait. This causes the earlier message to disappear entirely, causing obvious issues in the coherence protocol. 

**Affects version**
State which version of gem5 this bug was found in. If on the develop branch state the Commit revision ID you are working.

Version 22.1.0.0 

**gem5 Modifications**
If you have modified gem5 in some way please state, to the best of your ability, how it has been modified.

I have implemented a custom coherence protocol using Ruby. 

**To Reproduce**
Steps to reproduce the behavior. Please assume starting from a clean repository:

Unfortunately, I am not sure how to reproduce these bugs without our coherence protocol. However, I believe it is inherent in the design of these mechanisms based on the source code that these errors could arise if multiple messages arrive on the same channel and are deferred. 

**Terminal Output**
If applicable, add the terminal output here. If long, only include the relevant lines.
Please put the terminal output in code blocks. I.e.:

```shell
#Terminal output here#
```

**Expected behavior**

**Host Operating System**
Ubuntu 22.04, Mac OS X, etc.

**Host ISA**
ARM, X86, RISC-V, etc.

**Compiler used**
State which compiler was used to compile gem5. Please include the compiler version.

**Additional information**
Add any other information which does not fit in the previous sections but may be of use in fixing this bug.

**Comment by powerjg** [comment]
Thanks for bringing this to the attention of the gem5 community! I think that most of the behavior you're seeing is expected (though there may be a bug if messages are overwritten in the stall queue). So, until we have more evidence of a bug (e.g., a reproducible error or some specific code that could be the culprit), I'm going to convert this to a discussion. I've included some further thoughts below.

> recycle: recycle moves the deferred request from the head of the queue to the tail to allow other messages to be processed immediately. I have encountered a case where this reordered deferred messages on the same message channel (for example, when there were two messages on the same network). When the receiving cache can later observe the deferred messages, the messages are observed out of order, causing the coherence protocol to believe the later message was sent before the earlier message. This causes a protocol deadlock in Ruby.

This is expected behavior in Ruby. In fact, generally it is best practice that your protocol can deal with messages out of order. The default for the network is to also allow messages to appear out of order (e.g., what happens if a lower priority virtual channel is more congested than a higher priority virtual channel). 

> stall_and_wait: stall_and_wait moves the deferred request into a separate structure tagged by an address. I have found that if there coherence protocol attempts to defer multiple messages using stall_and_wait, the earlier message which was deferred is overwritten by later calls to stall_and_wait. This causes the earlier message to disappear entirely, causing obvious issues in the coherence protocol.

This could be a bug. As far as I know, when you use `stall_and_wait` all messages should be awoken when you call `wakeUpAllBuffers`. Now, there is some serious subtlety in `wakeUpBuffers` vs `wakeUpAllBuffers`, which I would have to dig into the implementation to see exactly how they work. If there are messages that are "lost", this would be both a bug in Ruby and a memory leak. If you could point to the code that you think isn't right, I could take a closer look.

That said, if you use `stall_and_wait` you'll still have the same reordering problem as `recycle`. I.e., there is no guarantee of ordering when messages are awoken in the stall queue or between new incoming messages being processed and messages in the stall queue.
